# Heavily inspired (copied) by rust-analyzer CI.

name: CI
on:
  pull_request:
  push:
    branches:
    - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_HOME: /cargo
  CARGO_TARGET_DIR: /cargo_target
  RUSTFLAGS:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pepyakin/bfb:1.0.0
    steps:
      - name: Diagnostics
        run: (ls -lha /root ; ls -lha /root/.rustup ; cat /root/.rustup/settings.toml ; ls -lha /sugondat ; ls -lha /cargo ; export)
      - name: Build
        working-directory: /sugondat
        shell: bash
        run: su -c "/cargo/bin/cargo +nightly-2023-10-16 build --release -p sugondat-node"
