# Heavily inspired (copied) by rust-analyzer CI.

name: CI
on:
  pull_request:
  push:
    branches:
    - master

env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub -W rust-2021-compatibility"

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72

    - name: Compile
      run: cargo test --no-run --locked

    - name: Test
      run: cargo test -- --nocapture --quiet
