# Heavily inspired (copied) by rust-analyzer CI.

name: CI
on:
  pull_request:
  push:
    branches:
    - master

env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTC_VERSION: nightly-2023-10-16

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pepyakin/bfb:1.0.0
    steps:
      - name: Rust re-install
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTC_VERSION
      - name: Build
        run: (cd /sugondat && /root/.cargo/bin/cargo +nightly-2023-10-16 build --release -p sugondat-node)
