# Heavily inspired (copied) by rust-analyzer CI.

name: CI
on:
  pull_request:
  push:
    branches:
    - master

env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pepyakin/bfb:1.0.0
    steps:
      - name: Build
        run: (cd /sugondat && cargo build --release -p sugondat-node)
